# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20160913_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
    ]
