# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_contact_main_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='main_contact',
            field=models.BooleanField(),
        ),
    ]
