# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_auto_20160920_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
    ]
