# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 00:00
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_auto_20160921_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#CCCCCC', max_length=18),
        ),
        migrations.AddField(
            model_name='app',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#CD0000', max_length=18),
        ),
    ]
