# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0003_auto_20160913_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=30)),
                (
                    'enterprise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='enterprise.App',
                        verbose_name='Aplicativo'
                    )
                ),
            ],
            options={
                'verbose_name': 'Se\xe7\xe3o',
                'verbose_name_plural': 'Se\xe7\xf5es',
            },
        ),
    ]
