# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_auto_20160913_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
