# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 05:32
from __future__ import unicode_literals

import appdata.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_contact_main_contact'),
        ('appdata', '0003_section_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.App', verbose_name='Aplicativo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=appdata.models.product_directory_path)),
                ('caption', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.Product')),
            ],
        ),
    ]
