# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0005_auto_20160913_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(to='appdata.Section', verbose_name='se\xe7\xf5es'),
        ),
    ]
