# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0006_product_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=20, verbose_name='refer\xeancia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=120, verbose_name='descri\xe7\xe3o '),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='t\xedtulo'),
        ),
    ]
