# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0009_auto_20160913_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='descri\xe7\xe3o breve'),
        ),
    ]
