# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 15:01
from __future__ import unicode_literals

import appdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0011_productimage_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'imagem do produto', 'verbose_name_plural': 'imagens do produto'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(max_length=100, verbose_name='legenda'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=appdata.models.product_directory_path, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='main_image',
            field=models.BooleanField(default=False, verbose_name='imagem inicial'),
        ),
    ]
