# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_auto_20160913_1220'),
        ('appdata', '0012_auto_20160913_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, verbose_name='refer\xeancia')),
                ('title', models.CharField(max_length=50, verbose_name='t\xedtulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o')),
                ('is_active', models.BooleanField(default=False, verbose_name='ativo')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.App', verbose_name='Aplicativo')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveProduct',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('appdata.product',),
        ),
        migrations.CreateModel(
            name='ActiveSection',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('appdata.section',),
        ),
        migrations.AddField(
            model_name='highlight',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appdata.Product'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.Section'),
        ),
    ]
