# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0014_auto_20160914_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.App', verbose_name='aplicativo'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appdata.Product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.Section', verbose_name='se\xe7\xe3o'),
        ),
    ]
