# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:12
from __future__ import unicode_literals

import appdata.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0015_auto_20160920_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=appdata.models.product_directory_path, verbose_name='imagem')),
                ('caption', models.CharField(max_length=100, verbose_name='legenda')),
                ('main_image', models.BooleanField(default=False, verbose_name='imagem inicial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='highlight',
            options={'verbose_name': 'Destaque'},
        ),
        migrations.AlterField(
            model_name='highlight',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_highlights', to='enterprise.App', verbose_name='aplicativo'),
        ),
        migrations.AddField(
            model_name='highlightimage',
            name='highlight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.Highlight', verbose_name='destaque'),
        ),
    ]
