# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_auto_20160921_1912'),
        ('appdata', '0016_auto_20160921_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightimage',
            options={'verbose_name': 'Imagem para destaque', 'verbose_name_plural': 'Imagens para destaque'},
        ),
        migrations.AlterField(
            model_name='highlight',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appdata.Section', verbose_name='se\xe7\xe3o'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('enterprise', 'reference')]),
        ),
    ]
