# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0017_auto_20160921_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
