# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:27
from __future__ import unicode_literals

import appdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0019_auto_20160922_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(upload_to=appdata.models.highlight_directory_path),
        ),
    ]
